<?php 
$_aClassFiles = array( 
    "LateCachingForFeeds_Bootstrap"=> LateCachingForFeeds_Registry::$sDirPath . "/include/LateCachingForFeeds_Bootstrap.php", 
    "LateCachingForFeeds_SimplePie_Cache"=> LateCachingForFeeds_Registry::$sDirPath . "/include/custom_simplepie/LateCachingForFeeds_SimplePie_Cache.php", 
    "LateCachingForFeeds_SimplePie_Cache_Transient"=> LateCachingForFeeds_Registry::$sDirPath . "/include/custom_simplepie/LateCachingForFeeds_SimplePie_Cache_Transient.php", 
    "LateCachingForFeeds_SimplePie_Cache_Transient_Normal"=> LateCachingForFeeds_Registry::$sDirPath . "/include/custom_simplepie/LateCachingForFeeds_SimplePie_Cache_Transient_Normal.php", 
    "LateCachingForFeeds_SimplePieSubClassSetter"=> LateCachingForFeeds_Registry::$sDirPath . "/include/main/LateCachingForFeeds_SimplePieSubClassSetter.php", 
    "LateCachingForFeeds_Event_WPCron_RenewCaches"=> LateCachingForFeeds_Registry::$sDirPath . "/include/main/event/wpcron/LateCachingForFeeds_Event_WPCron_RenewCaches.php", 
    "LateCachingForFeeds_Debug"=> LateCachingForFeeds_Registry::$sDirPath . "/include/utility/LateCachingForFeeds_Debug.php", 
    "LateCachingForFeeds_Utility"=> LateCachingForFeeds_Registry::$sDirPath . "/include/utility/LateCachingForFeeds_Utility.php", 
    "LateCachingForFeeds_WPUtility"=> LateCachingForFeeds_Registry::$sDirPath . "/include/utility/LateCachingForFeeds_WPUtility.php", 
    "LateCachingForFeeds_AdminPageFramework_Debug"=> LateCachingForFeeds_Registry::$sDirPath . "/include/utility/apf/LateCachingForFeeds_AdminPageFramework_Debug.php", 
    "LateCachingForFeeds_AdminPageFramework_Utility"=> LateCachingForFeeds_Registry::$sDirPath . "/include/utility/apf/LateCachingForFeeds_AdminPageFramework_Utility.php", 
    "LateCachingForFeeds_AdminPageFramework_Debug_Base"=> LateCachingForFeeds_Registry::$sDirPath . "/include/utility/apf/LateCachingForFeeds_AdminPageFramework_Debug.php", 
    "LateCachingForFeeds_AdminPageFramework_Debug_Log"=> LateCachingForFeeds_Registry::$sDirPath . "/include/utility/apf/LateCachingForFeeds_AdminPageFramework_Debug.php", 
    "LateCachingForFeeds_AdminPageFramework_Utility_VariableType"=> LateCachingForFeeds_Registry::$sDirPath . "/include/utility/apf/LateCachingForFeeds_AdminPageFramework_Utility.php", 
    "LateCachingForFeeds_AdminPageFramework_Utility_String"=> LateCachingForFeeds_Registry::$sDirPath . "/include/utility/apf/LateCachingForFeeds_AdminPageFramework_Utility.php", 
    "LateCachingForFeeds_AdminPageFramework_Utility_Array"=> LateCachingForFeeds_Registry::$sDirPath . "/include/utility/apf/LateCachingForFeeds_AdminPageFramework_Utility.php", 
    "LateCachingForFeeds_AdminPageFramework_Utility_ArrayGetter"=> LateCachingForFeeds_Registry::$sDirPath . "/include/utility/apf/LateCachingForFeeds_AdminPageFramework_Utility.php", 
    "LateCachingForFeeds_AdminPageFramework_Utility_ArraySetter"=> LateCachingForFeeds_Registry::$sDirPath . "/include/utility/apf/LateCachingForFeeds_AdminPageFramework_Utility.php", 
    "LateCachingForFeeds_AdminPageFramework_Utility_Path"=> LateCachingForFeeds_Registry::$sDirPath . "/include/utility/apf/LateCachingForFeeds_AdminPageFramework_Utility.php", 
    "LateCachingForFeeds_AdminPageFramework_Utility_URL"=> LateCachingForFeeds_Registry::$sDirPath . "/include/utility/apf/LateCachingForFeeds_AdminPageFramework_Utility.php", 
    "LateCachingForFeeds_AdminPageFramework_Utility_File"=> LateCachingForFeeds_Registry::$sDirPath . "/include/utility/apf/LateCachingForFeeds_AdminPageFramework_Utility.php", 
    "LateCachingForFeeds_AdminPageFramework_Utility_SystemInformation"=> LateCachingForFeeds_Registry::$sDirPath . "/include/utility/apf/LateCachingForFeeds_AdminPageFramework_Utility.php", 
    "LateCachingForFeeds_AdminPageFramework_Utility_HTMLAttribute"=> LateCachingForFeeds_Registry::$sDirPath . "/include/utility/apf/LateCachingForFeeds_AdminPageFramework_Utility.php", 
);
